;//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
;//ƒV[ƒ“–¼	Fw‚½‚ß‚¢‚«‚Ì“úíx
;//file–¼	F0120
;//“oêl•¨	FålŒöArˆäA‰Ô‘òA‚»‚Ì‘¼ƒNƒ‰ƒXƒƒCƒgAˆãÒ
;//•‘•		F§•
;//“ú•t		F7Œ16“ú
;//ŠÔ		FŒßŒã1415‚­‚ç‚¢
;//êŠ		FEŠw‰€/‹³º EŠw‰€/‘ÌˆçŠÙ
;//—\‘z—e—Ê	F‘S‘Ì‚ğ’Ê‚µ‚Ä10~15K‘OŒã
;//”õl		FålŒöˆêlÌ‹“_
;//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
*0120_TOP
;{SceneSet ‚½‚ß‚¢‚«‚Ì“úí}

;//m:‘ÌŒ±”Å”ÍˆÍ‘‚«–ß‚µÏ‚İ

;//m:‰Ô‘ò‚Ærˆä‚ÌƒWƒƒ[ƒW‚Piã’…–³‚µj‚ğg—p‚µ‚½‚Ì‚Ågra‚É—v’Ç‰Á‚Å‚·B’Êí‚Ì‚İ‚ÅƒAƒbƒv‚Íg‚Á‚Ä‚Ü‚¹‚ñ

;//šschool01a ŠwZ‹³ºE’©’‹ ‚Æ‚è‚ ‚¦‚·01‚ğ“\‚é
[bg storage="school01a"][trans_c cross time=500]
[quake_bg xy m]

;//seA062.ogg
[se buf=0 storage="seA062"]

;//ƒVƒXƒeƒ€ƒAƒCƒRƒ“•ƒƒbƒZ[ƒWƒEƒBƒ“ƒhƒE•\¦
[sysbt_meswin]

*1005|
[fc]
[ns]Makoto[nse]
"Uwaa!"[pcms]

*1006|
[fc]
The sound of a chair falling over echoed loudly behind me.[pcms]

*1007|
[fc]
I stood up quickly, as if to escape the sensation of falling.[pcms]

*1007a|
[fc]
A dull headache, like dizziness, lingered faintly.[pcms]

;//BGM06.ogg
[bgm storage="BGM06"]

*1008|
[fc]
It felt like there had been some kind of serious emergency.[pcms]

*1009|
[fc]
It was the kind that wouldn't be surprising if it had killed me...[pcms]

*1010|
[fc]
[ns]Makoto[nse]
"..."[pcms]

*1011|
[fc]
All I could see in my field of vision was the silent classroom.[pcms]

*1012|
[fc]
No one else was in sight. I was alone in the classroom.[pcms]

*1013|
[fc]
Dying in this situation would be quite difficult, I suppose.[pcms]

*1014|
[fc]
Unless I jumped out of a window or hit my head on the corner of a desk[r]
and died... it didn't seem like an emergency situation.[pcms]

*1015|
[fc]
[ns]Makoto[nse]
"A dream... perhaps..."[pcms]

*1016|
[fc]
It seems I must have dozed off.[pcms]

*1017|
[fc]
It must have been a nightmare. I can't remember the content, but my[r]
heart is pounding fiercely.[pcms]

*1018|
[fc]
I remember feeling something refreshing and pleasant, but I can't[r]
quite put my finger on what it was.[pcms]

*1019|
[fc]
I feel like it was a dream about flying... Did I fall from there?[pcms]

*1020|
[fc]
If I were to interpret the dream, nine times out of ten, it would[r]
yield an unfavorable result.[pcms]

*1021|
[fc]
The sky represents my desire for freedom, and falling from there means[r]
failure...[pcms]

*1022|
[fc]
That it doesn't bring up any frustration...[pcms]

*1023|
[fc]
I can't explain the intense beating of my heart, but let's leave it at[r]
that.[pcms]

*1024|
[fc]
[ns]Makoto[nse]
"..."[pcms]

*1025|
[fc]
While setting the fallen chair back in place, I waited for my head to[r]
clear.[pcms]

*1026|
[fc]
It was fortunate that no one else was in the classroom, but why was I[r]
left alone?[pcms]

*1027|
[fc]
You wouldn't end up alone in a classroom unless you arrived first[r]
thing in the morning or left last, or something like that.[pcms]

*1028|
[fc]
If everyone in the world had died without my knowledge, leaving me as[r]
the last person alive... what would I do?[pcms]

*1029|
[fc]
Maybe I wandered into a multiverse, or it's Japan 40 million years[r]
ago...[pcms]

*1030|
[fc]
When I glanced at the blackboard, I saw the teacher's note saying to[r]
gather in the gymnasium.[pcms]

[fadeoutbgm time=500]
;^<SoundRun 0,Stop,ON,2000>

*1031|
[fc]
[ns]Makoto[nse]
"Ah..."[pcms]

[bgm storage="BGM03"]
;//ôbgm03@

*1032|
[fc]
That's when I remembered this morning's homeroom.[pcms]

*1033|
[fc]
I wasn't paying much attention, but I think there was talk about going[r]
to the gymnasium.[pcms]

*1034|
[fc]
The timing fits perfectly.[pcms]

*1035|
[fc]
It seems everyone left without me.[pcms]

*1036|
[fc]
To be honest, my body felt incredibly sluggish. But I couldn't just[r]
not go.[pcms]

*1037|
[fc]
While doubting if I could still make it, I left the classroom and[r]
headed for the gymnasium.[pcms]

;//#_ƒuƒ‰ƒbƒNƒAƒEƒg
[black_toplayer][trans_c cross time=1000][hide_chara_int]

;//BGMƒtƒF[ƒhƒAƒEƒg
[fadeoutbgm time=500]
;<SoundFade 0,3000>

;//šschool07a ‘ÌˆçŠÙ
[bg storage="school07a"][trans_c cross time=500]

;//Ÿ‚r‚d@ŠwZ‚Ì‚´‚í‚ß‚«
;//seG003.ogg
[se buf=0 storage="seG003"]

;//bgm03.ogg
;//<SoundLoad 0,bgm03"]

*1038|
[fc]
Entering the gymnasium, a lukewarm breeze was generated by the heat of[r]
people and the difference in air pressure from outside.[pcms]

*1039|
[fc]
It's that stuffy feeling you get when you approach a crowd of people.[pcms]

*1040|
[fc]
I'm not particularly fond of it, but you can't complain about such[r]
things in communal life.[pcms]

*1041|
[fc]
Seeing everyone chatting away, it didn't seem like a very disciplined[r]
gathering.[pcms]

*1042|
[fc]
Inside the gymnasium, people were gathered like at a meeting, forming[r]
lines by class.[pcms]

*1043|
[fc]
And at the head of those lines sat a nurse in a white coat.[pcms]

*1044|
[fc]
It was that routine vaccination again.[pcms]

*1045|
[fc]
It's not for influenza or tuberculosis.[pcms]

;//‚±‚±‚ÉAƒEƒBƒ‹ƒX‚Ì‰æ‘œ‚ğ·‚µ‚à‚¤B
;//‚Ç‚¤‚à‚±‚±‚Í‰æ‘œ‚ª‚È‚­‚Ä‚æ‚­‚È‚¢B
;//‰æ‘œ‚Ì–¼‘O‚Í mob_N011.bmp

;//BGM‘¦’â~
[fadeoutbgm time=500]

;//seB023.ogg
[se buf=0 storage="seB023"]

;//ƒVƒXƒeƒ€ƒAƒCƒRƒ“•ƒƒbƒZ[ƒWƒEƒBƒ“ƒhƒEÁ‹
[sysbt_meswin clear]

;//s:‚±‚±‚ÉƒCƒxƒ“ƒgw’è‚µ‚Ä‚¨‚¢‚Ä‰º‚³‚¢B
[evcg storage="mob_N011a"][trans_c cross time=300]
[evcg storage="mob_N011b"][trans_c cross time=300]
[evcg storage="mob_N011a"][trans_c cross time=300]
[evcg storage="mob_N011b"][trans_c cross time=300]
[evcg storage="mob_N011a"][trans_c cross time=300]
[wait_c time=500]

;//ƒVƒXƒeƒ€ƒAƒCƒRƒ“•ƒƒbƒZ[ƒWƒEƒBƒ“ƒhƒE•\¦
[sysbt_meswin]

*1046|
[fc]
It's that infectious disease vaccination that recently became[r]
mandatory for everyone regardless of gender or age.[pcms]

*1047|
[fc]
It's an important vaccination that provides resistance to a certain[r]
virus, the one that changed everyone's lives... that virus.[pcms]

;//bgm03.ogg
[bgm storage="BGM03"]

;//s:‚±‚±‚Å”wŒi‚Ö–ß‚·
;//šschool07a ‘ÌˆçŠÙ
[bg storage="school07a"][trans_c cross time=500]

*1048|
[fc]
I completely forgot about the talk our homeroom teacher gave this[r]
morning and ended up sleeping through it.[pcms]

*1049|
[fc]
I wonder what would happen if I were late for the vaccination time.[pcms]

*1050|
[fc]
If I have to go to the hospital by myself to get the shot, it would be[r]
quite a hassle.[pcms]

*1051|
[fc]
And then the homeroom teacher would get nagged by the vice-principal[r]
because of me.[pcms]

*1052|
[fc]
It's my fault for sleeping, so I can't really complain, but causing[r]
trouble for someone else feels quite burdensome.[pcms]

*1053|
[fc]
I quicken my pace a bit and walk towards the line formed by my class.[pcms]

*1054|
[fc]
The person who thought of collective responsibility must really[r]
understand human psychology; I felt like praising them.[pcms]

;//Ÿ‚±‚Ì•Ó‚è‚Årˆä‚â‰Ô‘ò‚Ì—§‚¿ƒLƒƒƒ‰A@ˆê˜Y‚Ì—§‚¿ƒLƒƒƒ‰‚ğo‚µ‚Ä‰º‚³‚¢B

[ChrSetEx layer=5 chbase="ar1_ja1"][ChrSetParts layer=5 chface="F1_ar01"][ChrSetXY layer=5 x=300 y=0][trans_c cross time=150]
[wait_c time=500]
[chara_int][trans_c cross time=150]
[wait_c time=500]
[ChrSetEx layer=5 chbase="so1_se_a"][ChrSetParts layer=5 chface="F1_so01a"][ChrSetXY layer=5 x=340 y=0][trans_c cross time=150]
[wait_c time=500]
[chara_int][trans_c cross time=150]
[wait_c time=500]
[ChrSetEx layer=5 chbase="ha1_ja1_a"][ChrSetParts layer=5 chface="F1_ha01"][ChrSetXY layer=5 x=330 y=0][trans_c cross time=150]
[wait_c time=500]
[chara_int][trans_c cross time=150]
[wait_c time=500]

*1055|
[fc]
When I got to the class line, I could see that the students were lined[r]
up in order of attendance numbers.[pcms]

*1056|
[fc]
For all-school assemblies, we line up by height, but they must be[r]
checking the attendance book as they proceed.[pcms]

*1057|
[fc]
My name, Nakazawa Makoto, with "Na", doesn't seem to have come up yet.[pcms]

*1058|
[fc]
I don't mind being last, but following the order is easiest.[pcms]

;//Ÿ‚±‚Ì•Ó‚è‚Å“ñl‚Ì•\î•Ï‰»‚Æ‚©

*1059|
[fc]
As I try to line up in my spot, I feel the gazes of my classmates on[r]
me.[pcms]

*1060|
[fc]
The gazes range from somewhat guilty to blatantly malicious.[pcms]

*1061|
[fc]
But I had already become completely accustomed to those gazes.[pcms]

*1062|
[fc]
Without caring about anything, I join the line where I'm supposed to[r]
be and stand there.[pcms]

*1063|
[fc]
[ns]Homeroom Teacher[nse]
"What were you doing, Nakazawa! Hurry up and line up!"[pcms]

;//Ÿ’S”C‹³t‚Í’j‚É‚µ‚Ä‚¨‚«‚Ü‚·

*1064|
[fc]
[ns]Makoto[nse]
"I was sleeping, sorry."[pcms]

;//Ÿ‚±‚±‚Å‰Ô‘ò‚Ìˆêl—§‚¿‚ÉH
[ChrSetEx layer=5 chbase="ha1_ja1_a"][ChrSetParts layer=5 chface="F1_ha11"][ChrSetXY layer=5 x=330 y=0][trans_c cross time=150]

*1065|
[fc]
I could hear a nasty laugh from a group of girls lined up nearby.[pcms]

*1066|
[fc]
They're the followers of Arai, the soccer team's ace.[pcms]

*1067|
[fc]
The boss of the girls, I think her name was Hanazawa, but I'm not[r]
interested enough to be sure.[pcms]

*1068|
[fc]
Apparently, under their direction, I was left alone in the classroom.[pcms]

;//Ÿ—§‚¿ŠGÁ‚µ
[chara_int][trans_c cross time=150]

*1069|
[fc]
The rest of my classmates either look away or give me a pitying[r]
glance.[pcms]

*1070|
[fc]
I don't necessarily want their help, but being looked at with such[r]
eyes is a bit offensive.[pcms]

*1071|
[fc]
[ns]Homeroom Teacher[nse]
"You guys should have the decency to wake up anyone sleeping in the[r]
classroom!"[pcms]

*1072|
[fc]
Our homeroom teacher, who can't read the room, doesn't even realize[r]
that I'm isolated in the class.[pcms]

*1073|
[fc]
He's loud, but he's actually quite a pushover inside, so he wouldn't[r]
be able to handle a bullying problem.[pcms]

*1074|
[fc]
Yes, my place in the class wasn't exactly comfortable.[pcms]

;//ŸrˆäA‰Ô‘ò—§‚¿ŠG
[ChrSetEx layer=3 chbase="ha1_ja1_a"][ChrSetParts layer=3 chface="F1_ha02"][ChrSetXY layer=3 x=30 y=0]
[ChrSetEx layer=4 chbase="ar1_ja1"][ChrSetParts layer=4 chface="F1_ar02"][ChrSetXY layer=4 x=600 y=0][trans_c cross time=150]

*1075|
[fc]
I've been bullied since I got into this class.[pcms]

*1076|
[fc]
I'm not big. In fact, I'm short.[pcms]

*1077|
[fc]
I'm not fat, but few people would think I'm strong just by looking at[r]
me.[pcms]

*1078|
[fc]
I'm good at running but generally bad at ball games, and my throwing[r]
distance is so bad I lose to girls.[pcms]

*1079|
[fc]
I can barely float in water when swimming; calling that swimming would[r]
be a stretch.[pcms]

*1080|
[fc]
My face and gestures are weak and effeminate; I've been told that[r]
before.[pcms]

*1081|
[fc]
But no one has ever tried to hit me or take money from me; there's[r]
been no blatant criminal behavior against me.[pcms]

;//Ÿrˆä—§‚¿ŠG‚Æ‚©
[chara_int]
[ChrSetEx layer=5 chbase="ar1_ja1"][ChrSetParts layer=5 chface="F1_ar02"][ChrSetXY layer=5 x=300 y=0][trans_c cross time=150]

*1082|
[fc]
Arai from the soccer team is a promising player scouted by[r]
professionals, so he probably doesn't want to cause any trouble.[pcms]

*1083|
[fc]
But even so, I couldn't even think about messing him up badly.[pcms]

*1084|
[fc]
I could attempt suicide and leave a note saying I was bullied by Arai,[r]
maybe the media would make a fuss, but somehow, I don't really care.[pcms]

;//Ÿ—§‚¿ŠGÁ‚µ
[chara_int][trans_c cross time=150]

*1085|
[fc]
[ns]Homeroom Teacher[nse]
"Hey, Nakazawa, it's your turn. Don't space out."[pcms]

*1086|
[fc]
As I was thinking about that, it became my turn for the vaccination.[pcms]

*1087|
[fc]
The teacher whispered something to the nurse when it was my turn.[pcms]

*1088|
[fc]
The nurse looked a bit shaken, with a complicated expression on her[r]
face.[pcms]

*1089|
[fc]
I sat down, rolled up my right sleeve, and extended my arm over the[r]
desk, waiting for the injection needle.[pcms]

*1090|
[fc]
The nurse, who had been forewarned by the teacher's whisper, checked[r]
the "barcode" engraved on my right arm without surprise.[pcms]

*1091|
[fc]
The nurse operated the handheld device to scan the barcode.[pcms]

*1092|
[fc]
I'd like to see what kind of display it shows just once, but it's[r]
something that the person themselves can't see.[pcms]

*1093|
[fc]
After checking the device, the nurse slowly began to prepare the[r]
injection needle.[pcms]

*1094|
[fc]
It had been a while since I saw someone react to this barcode.[pcms]

*1095|
[fc]
But still, I'm already sick of it.[pcms]

;//‚±‚Ì•Ó‚è‚É‚àAƒEƒBƒ‹ƒX‚Ì‰æ‘œ‚Æ‚©
;//‰æ‘œ‚Ì–¼‘O‚Í mob_N011.bmp‚ç‚µ‚¢‚Å‚·
;//#_”’ƒtƒ‰
[evcg”’ƒtƒ‰ storage="mob_N011a" time=300]

*1096|
[fc]
They stuck the injection needle into my arm.[pcms]

*1097|
[fc]
I felt more disgust than pain.[pcms]

*1098|
[fc]
I don't know if it's inactivated or attenuated, but it felt creepy to[r]
have that virus put into my body.[pcms]

*1099|
[fc]
It's not so much scary as it is unpleasant.[pcms]

;//šschool07a ‘ÌˆçŠÙ
[bg storage="school07a"][trans_c cross time=500]

*1100|
[fc]
[ns]Homeroom Teacher[nse]
"Wait, wait a minute, Nakazawa!"[pcms]

*1101|
[fc]
As the vaccination ended and I stood up from the chair to leave the[r]
line, the homeroom teacher called out to me.[pcms]

*1102|
[fc]
The nurse was frowning across the desk.[pcms]

*1103|
[fc]
I wonder what it was, was there something wrong with the injection?[pcms]

*1104|
[fc]
The homeroom teacher peeled something off my back. Apparently, there[r]
had been a paper stuck there.[pcms]

*1105|
[fc]
"I am infected. I'm raping my own sister."[pcms]

;//seG002.ogg
[se buf=0 storage="seG002"]

;//Ÿ‰Ô‘ò—§‚¿ŠG
[ChrSetEx layer=5 chbase="ha1_ja1_a"][ChrSetParts layer=5 chface="F1_ha11"][ChrSetXY layer=5 x=330 y=0][trans_c cross time=150]

*1106|
[fc]
I could hear them snickering.[pcms]

[chara_int][trans_c cross time=150]

*1107|
[fc]
They say conflicts only happen with someone on your own level, and I[r]
thought that was absolutely true.[pcms]

*1108|
[fc]
[ns]Homeroom Teacher[nse]
"Th-this is... not good..."[pcms]

*1109|
[fc]
Looking at the homeroom teacher muttering in a low voice, I thought to[r]
myself, as expected.[pcms]

;//seƒtƒF[ƒh’â~
[stopse buf=0]
;<SoundFade 2,OUT,3000>
;//BGMƒtƒF[ƒhƒAƒEƒg
[fadeoutbgm time=500]
;<SoundFade 0,3000>

;//#_ƒuƒ‰ƒbƒNƒAƒEƒg
[black_toplayer][trans_c cross time=1000][hide_chara_int]

;//ƒuƒƒbƒN0130‚Öjump
[jump storage="0130.ks" target=*0130_TOP]

;//QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ

